project:
  type: manuscript

manuscript:
  article: index.qmd

format:
  html:
    comments:
      hypothesis: true
    toc: true

  docx:
    toc: true
    number-sections: true
    highlight-style: github

  pdf: default

number-sections: true
bibliography: references.bib
